---

- name: Install necessary Packages
  apt:
    name: "{{ packages }}"

- name: Create backend directory
  file:
    path: "{{ bepath }}"
    state: directory
    mode: 0755

- name: Pull the backend files
  aws_s3:
    bucket: skillup-s3-jesidsantos
    object: "{{ beobject }}"
    dest: "{{ bepath }}/{{ beobject }}"
    mode: get

- name: Extract backend files to html
  unarchive:
   src: "{{ bepath }}/{{ beobject }}"
   dest: "{{ webpath }}"

- name: modify backend file
  lineinfile:
   path: "{{ webpath }}/index.html"
   regexp: '^My Private'
   line: 'My Private IP address is: {{ ansible_default_ipv4.address }}'

- name: Setup httpd service
  systemd:
    enabled: yes
    daemon_reload: yes
    name: sshd
    state: restarted